[package]
name = "geneagrab-core"
version = "4.0.0"
edition = "2021"

[dependencies]
geneagrab-plugin-core = { path = "../plugin_core", features = ["host"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
thiserror = "2.0.18"
chrono = "0.4.44"
extism = "1.13.0"
tokio = "1.50.0"
sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "macros",
    "with-chrono",
] }
serde_json = "1.0.149"
wreq = "5.3.0"
wreq-util = "2.2.6"
