[package]
name = "geneagrab-providers"
version = "4.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.19"
derive_builder = "0.20.2"
regex = "1.13.1"
quick-xml = { version = "0.39.4", features = ["serialize"] }
url = "2.5.8"
strum = { version = "0.28.0", features = ["derive"] }
scraper = "0.27.0"
async-trait = "0.1.91"
dates = { path = "../../dates" }
tokio = { version = "1.53.1", features = ["sync"] }



