//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneaGrab.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Core {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneaGrab.Strings.Core", typeof(Core).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpes-Maritimes Departmental Archives.
        /// </summary>
        internal static string Provider_AD06 {
            get {
                return ResourceManager.GetString("Provider.AD06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departmental Archives of Charente-Maritime.
        /// </summary>
        internal static string Provider_AD17 {
            get {
                return ResourceManager.GetString("Provider.AD17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departmental Archives of Deux-Sèvres and Vienne.
        /// </summary>
        internal static string Provider_AD79_86 {
            get {
                return ResourceManager.GetString("Provider.AD79-86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipal Archives of Nice.
        /// </summary>
        internal static string Provider_AMNice {
            get {
                return ResourceManager.GetString("Provider.AMNice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenati.
        /// </summary>
        internal static string Provider_Antenati {
            get {
                return ResourceManager.GetString("Provider.Antenati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpes-Maritimes Departmental Archives (CG06).
        /// </summary>
        internal static string Provider_CG06 {
            get {
                return ResourceManager.GetString("Provider.CG06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geneanet.
        /// </summary>
        internal static string Provider_Geneanet {
            get {
                return ResourceManager.GetString("Provider.Geneanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice Historique.
        /// </summary>
        internal static string Provider_NiceHistorique {
            get {
                return ResourceManager.GetString("Provider.NiceHistorique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string Registry_Name {
            get {
                return ResourceManager.GetString("Registry.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banns of marriage.
        /// </summary>
        internal static string Registry_Type_Banns {
            get {
                return ResourceManager.GetString("Registry.Type.Banns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baptisms.
        /// </summary>
        internal static string Registry_Type_Baptism {
            get {
                return ResourceManager.GetString("Registry.Type.Baptism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of baptisms.
        /// </summary>
        internal static string Registry_Type_BaptismTable {
            get {
                return ResourceManager.GetString("Registry.Type.BaptismTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Births.
        /// </summary>
        internal static string Registry_Type_Birth {
            get {
                return ResourceManager.GetString("Registry.Type.Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of births.
        /// </summary>
        internal static string Registry_Type_BirthTable {
            get {
                return ResourceManager.GetString("Registry.Type.BirthTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Registry_Type_Book {
            get {
                return ResourceManager.GetString("Registry.Type.Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burials.
        /// </summary>
        internal static string Registry_Type_Burial {
            get {
                return ResourceManager.GetString("Registry.Type.Burial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of burials.
        /// </summary>
        internal static string Registry_Type_BurialTable {
            get {
                return ResourceManager.GetString("Registry.Type.BurialTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral assembly table.
        /// </summary>
        internal static string Registry_Type_CadastralAssemblyTable {
            get {
                return ResourceManager.GetString("Registry.Type.CadastralAssemblyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral map.
        /// </summary>
        internal static string Registry_Type_CadastralMap {
            get {
                return ResourceManager.GetString("Registry.Type.CadastralMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral matrix.
        /// </summary>
        internal static string Registry_Type_CadastralMatrix {
            get {
                return ResourceManager.GetString("Registry.Type.CadastralMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral section states.
        /// </summary>
        internal static string Registry_Type_CadastralSectionStates {
            get {
                return ResourceManager.GetString("Registry.Type.CadastralSectionStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        internal static string Registry_Type_Catalogue {
            get {
                return ResourceManager.GetString("Registry.Type.Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Census.
        /// </summary>
        internal static string Registry_Type_Census {
            get {
                return ResourceManager.GetString("Registry.Type.Census", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communions.
        /// </summary>
        internal static string Registry_Type_Communion {
            get {
                return ResourceManager.GetString("Registry.Type.Communion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmations.
        /// </summary>
        internal static string Registry_Type_Confirmation {
            get {
                return ResourceManager.GetString("Registry.Type.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        internal static string Registry_Type_Death {
            get {
                return ResourceManager.GetString("Registry.Type.Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of deaths.
        /// </summary>
        internal static string Registry_Type_DeathTable {
            get {
                return ResourceManager.GetString("Registry.Type.DeathTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engrossments.
        /// </summary>
        internal static string Registry_Type_Engrossments {
            get {
                return ResourceManager.GetString("Registry.Type.Engrossments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parish family book.
        /// </summary>
        internal static string Registry_Type_LiberStatutAnimarum {
            get {
                return ResourceManager.GetString("Registry.Type.LiberStatutAnimarum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriages.
        /// </summary>
        internal static string Registry_Type_Marriage {
            get {
                return ResourceManager.GetString("Registry.Type.Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of marriages.
        /// </summary>
        internal static string Registry_Type_MarriageTable {
            get {
                return ResourceManager.GetString("Registry.Type.MarriageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        internal static string Registry_Type_Military {
            get {
                return ResourceManager.GetString("Registry.Type.Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Registry_Type_Minutes {
            get {
                return ResourceManager.GetString("Registry.Type.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newspaper.
        /// </summary>
        internal static string Registry_Type_Newspaper {
            get {
                return ResourceManager.GetString("Registry.Type.Newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notarial deeds.
        /// </summary>
        internal static string Registry_Type_Notarial {
            get {
                return ResourceManager.GetString("Registry.Type.Notarial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Registry_Type_Other {
            get {
                return ResourceManager.GetString("Registry.Type.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodical.
        /// </summary>
        internal static string Registry_Type_Periodical {
            get {
                return ResourceManager.GetString("Registry.Type.Periodical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Registry_Type_Protocol {
            get {
                return ResourceManager.GetString("Registry.Type.Protocol", resourceCulture);
            }
        }
    }
}
