[package]
edition = "2024"
name = "migration"
publish = false
rust-version = "1.85.0"
version = "4.0.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }

[dependencies.sea-orm-migration]
features = ["sqlx-sqlite", "runtime-tokio"]
version = "2.0.0-rc"
