[package]
name = "geneagrab-plugin-core"
version = "4.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
chrono = { version = "0.4.44", default-features = false, features = [
    "alloc",
    "serde",
] }
thiserror = "2.0.18"
derive_builder = "0.20.2"

# Optional dependencies
extism = { version = "1.0", optional = true }
extism-pdk = { version = "1.0", optional = true }
regex = { version = "1.12.3", optional = true }
quick-xml = { version = "0.39.2", features = ["serialize"], optional = true }
url = { version = "2.5.8", optional = true }
strum = { version = "0.28.0", features = ["derive"] }
scraper = { version = "0.27.0", optional = true }


[features]
host = ["dep:extism"]
guest = ["dep:extism-pdk", "dep:regex", "dep:url", "dep:scraper"]
protocols-zoomify = ["dep:quick-xml"]
protocols-iiif = []
protocols-ligeo = []
