[package]
name = "geneagrab-plugin-core"
version = "4.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.44", default-features = false, features = [
    "alloc",
    "serde",
] }
anyhow = "1.0"

# Optional dependencies
serde_json = { version = "1.0", optional = true }
extism = { version = "1.0", optional = true }
extism-pdk = { version = "1.0", optional = true }
derive_builder = "0.20.2"

[features]
host = ["dep:extism", "dep:serde_json"]
guest = ["dep:extism-pdk"]
